#!/bin/sh

JAVAC=${2:-${JAVAC:-javac}}

${JAVAC} -version 2>&1 | {
	read -r NAME VERSION

	printf "Current java (%s) version: %s\n" "$NAME" "$VERSION" >&2

	VERSION=${VERSION#\"}
	VERSION=${VERSION#1.}
	VERSION=${VERSION%%.*}

	test $VERSION -ge $1
	exit $?
}
